version: '2.3'


services:

  ipython-shell:
    build: .
    runtime: nvidia

    volumes:
      - ./data:/code/data
      - ./scripts:/code/scripts
      - ./annotations:/code/annotations
      - ./images:/code/images

    working_dir: /code

    stdin_open: true
    tty: true

    command: ipython --TerminalInteractiveShell.editing_mode=vi

  create-dataset:
    build: .
    runtime: nvidia

    volumes:
      - ./data:/code/data
      - ./scripts:/code/scripts
      - ./images:/code/images
      - ./test_images:/code/test_images
      - ./annotations:/code/annotations

    working_dir: /code

    stdin_open: true
    tty: true

    command: bash /code/scripts/download_process_data.sh


  train:
    build: .
    runtime: nvidia

    volumes:
      - ./data:/code/data
      - ./scripts:/code/scripts

    working_dir: /code

    stdin_open: true
    tty: true

    command: bash /code/scripts/train.sh

  export-model:
    build: .
    runtime: nvidia

    volumes:
      - ./data:/code/data
      - ./scripts:/code/scripts

    working_dir: /code
    stdin_open: true
    tty: true

    command: bash /code/scripts/export_model.sh