version: '2.3'


services:

  ipython-shell:
    build: .
    runtime: nvidia

    volumes:
      - ./data:/code/data
      - ./scripts:/code/scripts
      - ./annotations:/code/annotations
      - ./images:/code/images

    working_dir: /code

    stdin_open: true
    tty: true

    command: ipython --TerminalInteractiveShell.editing_mode=vi

  create-dataset:
    build: .
    runtime: nvidia

    volumes:
      - ./data:/code/data
      - ./scripts:/code/scripts
      - ./images:/code/images
      - ./test_images:/code/test_images
      - ./annotations:/code/annotations

    working_dir: /code

    stdin_open: true
    tty: true

    command: bash /code/scripts/download_process_data.sh


  train:
    build: .
    runtime: nvidia

    volumes:
      - ./data:/code/data
      - ./scripts:/code/scripts

    working_dir: /code

    stdin_open: true
    tty: true

    command: bash /code/scripts/train.sh

  tensorboard:
    build: .

    volumes:
      - ./data:/code/data

    working_dir: /code
    ports:
      - "6000:6006"

    stdin_open: true
    tty: true

    command: tensorboard --logdir data/train_data

  export-model:
    build: .
    runtime: nvidia

    volumes:
      - ./data:/code/data
      - ./scripts:/code/scripts

    working_dir: /code
    stdin_open: true
    tty: true

    command: bash /code/scripts/export_model.sh
    
  run-inference:
    build: .
    runtime: nvidia

    volumes:
      - ./data:/code/data
      - ./scripts:/code/scripts
      - ./test_images:/code/test_images
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1 
    working_dir: /code
    stdin_open: true
    tty: true

    command: python /code/scripts/run_inference.py